name: Release
on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update version in package.json with tag
              run: |
                  TAG="${GITHUB_REF/refs\/tags\/v/}"
                  echo "VERSION_TAG=${TAG}" >> $GITHUB_ENV
                  cat package.json | jq --arg VER $TAG '.version=$VER' > /tmp/package.json
                  cp /tmp/package.json ./package.json

            - name: Update package.json version in repository
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git add ./package.json
                  git commit -m "Release and bump to version v${{ env.VERSION_TAG }}"
                  git push origin HEAD:master

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Build VSIX
              run: |
                  npm ci
                  npm run compile
                  npx vsce package -o "./whack-a-mole-v${{ env.VERSION_TAG }}.vsix"

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: whack-a-mole-v${{ env.VERSION_TAG }}.vsix
