name: Release
on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Update version in package.json with tag
              run: |
                  TAG="${GITHUB_REF/refs\/tags\/v/}"
                  echo "VERSION_TAG=${TAG}" >> $GITHUB_ENV
                  cat package.json | jq --arg VER $TAG '.version=$VER' > /tmp/package.json
                  cp /tmp/package.json ./package.json

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 21

            - name: Build VSIX
              run: |
                  npm ci
                  npm run compile
                  npx vsce package -o "./whack-a-mole-v${{ env.VERSION_TAG }}.vsix"

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload to Release
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./whack-a-mole-v${{ env.VERSION_TAG }}.vsix
                  asset_name: whack-a-mole-v${{ env.VERSION_TAG }}.vsix
                  asset_content_type: application/zip

            - name: Update package.json version in repository
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git commit -am "Release and bump to version v${{ env.VERSION_TAG }}"
                  git push origin HEAD:master
